name: Publish to NPM

on:
    release:
        types: [created]
    workflow_dispatch:
        inputs:
            version:
                description: 'Version type to bump (patch, minor, major)'
                required: true
                default: 'patch'
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test --if-present

            - name: Build package
              run: npm run build

            - name: Bump version (manual trigger)
              if: github.event_name == 'workflow_dispatch'
              run: |
                  npm version ${{ github.event.inputs.version }} -m "chore: bump version to %s [skip ci]"
                  git push --follow-tags

            - name: Publish to NPM
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create GitHub Release (manual trigger)
              if: github.event_name == 'workflow_dispatch'
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ steps.package-version.outputs.version }}
                  release_name: Release v${{ steps.package-version.outputs.version }}
                  body: |
                      Automated release for version ${{ steps.package-version.outputs.version }}

                      See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
                  draft: false
                  prerelease: false
